#!/bin/bash

#d33vliter
######Variables#####
s="sudo"
il="sudo xbps-install -y"
#####################
clear

echo "|¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯|"
echo "| VoidBSP Installer |"
echo "|___________________|"
echo ""
echo ""
sleep 2s
echo "Introduzca contraseña para continuar"
sudo -k
if sudo true; then
	clear
	echo "Iniciando Instalación..."
	sleep 2s
else
	clear
	echo "Debe introduccir contraseña para continuar"
	exit 1
fi

#UPDATE
$s xbps-install -Sy

#ESENCIALES 
$il at-spi2-core base-devel p7zip xdg-user-dirs xorg gvfs gnome-keyring lxsession

#BASE
$il bspwm sxhkd polybar dmenu rofi scrot xsetroot xdo setxkbmap numlockx \
	dbus sakura elogind fuzzypkg fzf zoxide bat clipit pcmanfm

#PROGRAMAS ADICIONALES // AUDIO // TIPOGRAFIA // ETC

$il pulsemixer pipewire rtkit pfetch nerd-fonts lxappearance mpv arandr \
	neovim file-roller feh firefox gnome-themes-extra-gtk picom

#repos nonfree y multilib(tambien 32bit)
$il void-repo-{nonfree,multilib,multilib-nonfree}
$s xbps-install -Sy

#libs para juegos
$il libgcc-32bit libstdc++-32bit libdrm-32bit libglvnd-32bit freetype-32bit vulkan-loader-32bit

#firefox font fix
$s ln -s /usr/share/fontconfig/conf.avail/70-no-bitmaps.conf /etc/fonts/conf.d/
$s xbps-reconfigure -f fontconfig

clear
echo "Aplicando configuraciones..."
sleep 2s


#INICIAR SERVICIOS
$s ln -s /etc/sv/dbus /var/service/
$s rm -r /var/service/polkitd

#CONFIG
xdg-user-dirs-update

echo -e '#autostart
\nif [ -d "$HOME/.local/bin" ] ; then
\n    PATH="$HOME/.local/bin:$PATH"
\nfi
\npipewire &
\npipewire-pulse &
\nexec dbus-run-session bspwm'> $HOME/.xinitrc

#PIPEWIRE_CONFIG
$s mkdir -p /etc/pipewire/pipewire.conf.d
$s ln -s /usr/share/examples/wireplumber/10-wireplumber.conf /etc/pipewire/pipewire.conf.d/
$s ln -s /usr/share/examples/pipewire/20-pipewire-pulse.conf /etc/pipewire/pipewire.conf.d/

#archivos de config
yes | cp -rf .config/* ~/.config/
mkdir -p ~/.local/bin
yes | cp -r bash/_scripts/* ~/.local/bin/
yes | cp -r bash/.bashrc ~/.bashrc
yes | cp -r bash/.bash_profile ~/.bash_profile

#CARPETA PARA CAPTURES DE PANTALLA
mkdir $HOME/captures

mkdir $HOME/Wallpapers

#wallpaper
$s rm -r /usr/share/wall
$s mkdir /usr/share/wall
$s cp -r default_wallpaper/default.jpg.jpg /usr/share/wall/

###
clear
echo "Instalación de VoidBsp-term Completada"
echo "Pulse cualquiera tecla para continuar..."
read tecla
clear
