#!/bin/sh

###########
#AUTOSTART#
###########

#Monitor
xrandr --dpi 94

#Numkey
numlockx on

#Cursor
xsetroot -cursor_name tcross

#Keyboard
setxkbmap -layout us -variant intl

#Panel
pkill tint2
tint2 &
sleep 0.1 &&
xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" $(xdo id -n tint2)

#Keybind
pkill sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &


bspc monitor -d I II III IV
bspc config border_width         1
bspc config window_gap          12

#colores bordes
bspc config normal_border_color "#404040" #404040
bspc config focused_border_color "#A2A2A3" #A2A2A3


bspc config split_ratio          0.50
bspc config borderless_monocle   true
#bspc config gapless_monocle      true
bspc config single_monocle	true


bspc rule -a tint2 layer=below
