#!/usr/bin/env dash

###########
#AUTOSTART#
###########

#Monitor
xrandr --dpi 94

#wallpaper
pkill nitrogen
nitrogen --restore

#picom
pkill picom
picom -f -D 2 & 

#parcellite
pkill parcellite
parcellite -n &

#Numkey
numlockx on

#Cursor
xsetroot -cursor_name left_ptr

#Keyboard
setxkbmap -layout us -variant intl

#polkit
pkill /usr/bin/lxpolkit
/usr/bin/lxpolkit &

#polybar
pkill polybar
polybar &


#Keybind
pkill sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &


bspc monitor -d I II III IV
bspc config border_width         1
bspc config window_gap          12

#colores bordes
bspc config normal_border_color "#404040" #404040
bspc config focused_border_color "#FFFFFF" #A2A2A3


bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle	 true
